cmake -G Ninja \
    -S . \
    -B build \
    -DLLVM_DIR=/opt/llvm/lib/cmake/llvm \
    -DMLIR_DIR=/opt/llvm/lib/cmake/mlir \
    -DPython3_EXECUTABLE=$(which python3) \
    -DPython3_FIND_STRATEGY=LOCATION \
    -Dpybind11_DIR="${PYBIND11_CMAKE_DIR}" \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DMLIR_PYTHON_PACKAGE_DIR=${PTO_INSTALL_DIR} \
    -DCMAKE_INSTALL_PREFIX="$PTO_INSTALL_DIR" && ninja -C build && cmake --install build && cp build ../ -fr
